#!/bin/bash
#by sreekanth
BASE_DIR='/psql_db_backups'
YMD=$(date "+%Y-%m-%d")
DIR="$BASE_DIR/$YMD"
mkdir -p "$DIR"
cd "$DIR"

#remove files older than 2 days . you can increase backup retention
find "$BASE_DIR/" -mindepth 1 -type d -mtime +2 -print0 | xargs -0r rm -rfv

#Find the container names 
#docker ps --filter "name=postgres"
#

docker exec -i postgresql_1 /bin/bash -c "PGPASSWORD=mypassword pg_dump --username myuser mydb" | gzip -9 > "/$DIR/my_db-$(date +%Y-%m-%d).tar.gz"

#schedule this script as per your requirement
#for example add cron job to run every day midnight
#0 0 * * * /autobackup.sh
#to restore you can use below
# docker exec -i postgresql_1 /bin/bash -c "PGPASSWORD=mypassword  psql --username myuser mydb" < /path/dump.sql
